<?php include("../header.php"); ?>

	<h1>About Us</h1>
	<p>MRun is the running club at the University of Michigan. One of the founding clubs in the club running scene, MRun has since been a dominate force. Since its inception in 2004, the club has grown to a membership of over 200 dues-paying undergraduate and graduate students. This makes MRun not only the biggest, most popular, and fastest growing club on campus, but also the largest collegiate running club in the nation. Racing in varsity and club Cross Country and Track and Field meets across the Midwest, MRun is very competitive within collegiate running. The MRun men were national champions at the 2010 NIRCA Cross Country Championships meet, while the women completed the same feat in 2008. The MRun men and women have had top-five finishes within the NCTFA National Track and Field meet. Members of the club win races at the 5k, 10k, and marathon distances. MRun also caters to track &amp; field athletes and has year-round training for sprinters and field competitors. Because MRun competes in indoor and outdoor track, distance, sprint, and field event track athletes are able to travel around the country and compete in a long winter and spring season against club and varsity athletes.</p>
	<p>Although MRun is very competitive, it accomodates all types of runners, and thus <strong>all ability levels are welcome</strong>. There are no cuts, try-outs, or time trials to join the club. Whether you wish to compete against colleges nationwide, run in actual varsity races, or just show up a few times a week and run with friends, MRun is the right club for you. MRun provides more than just an outlet for running; it is also a large charitable organization, deeply involved within the community. This year alone the club as a whole raised over $11,000 for various local and national charities, including: Special Olympics, The American Cancer Society, and myTeam Triumph. MRun also provides a very social atmosphere which is inviting to newcomers.</p>

	<h1>Prospective Members</h1>
	<p>MRun welcomes all runners, regardless of speed or ability level. If you're a runner or would like to start running, MRun is the perfect club for you. All members of MRun have one thing in common: they love to run!</p>
	<p>MRun offers daily training runs of 3, 5, and 7 miles every weekday, as well as a long run of 8-12 miles on Sundays (more training information, including time and location, is available on the <a target="blank" href="http://mrun.clubrunning.org/about/faq.php">FAQ page</a>). If you are interested in racing, MRun travels to cross country meets in the fall as well as track and field meets in the winter and spring. Nothing in MRun is required, so you are free to attend as many or as few practices and meets as you would like. </p>
	<p>If you would like more information about MRun, just come to a weekday practice at 4:15 at the Central Campus Recreation Building. Also feel free to contact any officers from the <a href="http://mrun.clubrunning.org/about/contact.php">contact page</a> with any further questions.</p>
	<br />

<?php include("../footer.php"); ?>